// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/features/auth/domain/entity/login_response_entity.dart';
import 'src/features/notification/domain/entity/notification_response_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6018243409547234536),
    name: 'LoginResponseEntity',
    lastPropertyId: const obx_int.IdUid(6, 2686484623653868249),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7931118901384523702),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4836452831748749310),
        name: 'result',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5075742241257007117),
        name: 'message',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4928029442481556004),
        name: 'username',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3402551219169823713),
        name: 'mainCompanyId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2686484623653868249),
        name: 'comId',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 3038937951929850223),
    name: 'NotificationResponseEntity',
    lastPropertyId: const obx_int.IdUid(8, 5942078328082812468),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4230467337681304034),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5240475571186999295),
        name: 'asnNotId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2408486192760327983),
        name: 'asnNotLabel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5754470203237665665),
        name: 'asnNotDesc',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2515080422400628784),
        name: 'asnNotStatus',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5968763726602522110),
        name: 'asnNotAscCompId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2350165384987026883),
        name: 'asnNotCreatedDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5942078328082812468),
        name: 'asnNotCreatedBy',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 3038937951929850223),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [5712680126433048883],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      2072006378910712863,
      275920315943903261,
      841276810656626339,
      2716613263359126713,
      7926049975032927277,
      179102451878057031,
      7317608160021920532,
      2444968677864956431,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    LoginResponseEntity: obx_int.EntityDefinition<LoginResponseEntity>(
      model: _entities[0],
      toOneRelations: (LoginResponseEntity object) => [],
      toManyRelations: (LoginResponseEntity object) => {},
      getId: (LoginResponseEntity object) => object.id,
      setId: (LoginResponseEntity object, int id) {
        object.id = id;
      },
      objectToFB: (LoginResponseEntity object, fb.Builder fbb) {
        final resultOffset = object.result == null
            ? null
            : fbb.writeString(object.result!);
        final messageOffset = object.message == null
            ? null
            : fbb.writeString(object.message!);
        final usernameOffset = object.username == null
            ? null
            : fbb.writeString(object.username!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, resultOffset);
        fbb.addOffset(2, messageOffset);
        fbb.addOffset(3, usernameOffset);
        fbb.addInt64(4, object.mainCompanyId);
        fbb.addInt64(5, object.comId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final resultParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final messageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final usernameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final mainCompanyIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final comIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final object = LoginResponseEntity(
          result: resultParam,
          message: messageParam,
          username: usernameParam,
          mainCompanyId: mainCompanyIdParam,
          comId: comIdParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    NotificationResponseEntity:
        obx_int.EntityDefinition<NotificationResponseEntity>(
          model: _entities[1],
          toOneRelations: (NotificationResponseEntity object) => [],
          toManyRelations: (NotificationResponseEntity object) => {},
          getId: (NotificationResponseEntity object) => object.id,
          setId: (NotificationResponseEntity object, int id) {
            object.id = id;
          },
          objectToFB: (NotificationResponseEntity object, fb.Builder fbb) {
            final asnNotLabelOffset = object.asnNotLabel == null
                ? null
                : fbb.writeString(object.asnNotLabel!);
            final asnNotDescOffset = object.asnNotDesc == null
                ? null
                : fbb.writeString(object.asnNotDesc!);
            final asnNotCreatedByOffset = object.asnNotCreatedBy == null
                ? null
                : fbb.writeString(object.asnNotCreatedBy!);
            fbb.startTable(9);
            fbb.addInt64(0, object.id);
            fbb.addInt64(1, object.asnNotId);
            fbb.addOffset(2, asnNotLabelOffset);
            fbb.addOffset(3, asnNotDescOffset);
            fbb.addInt64(4, object.asnNotStatus);
            fbb.addInt64(5, object.asnNotAscCompId);
            fbb.addInt64(6, object.asnNotCreatedDate?.millisecondsSinceEpoch);
            fbb.addOffset(7, asnNotCreatedByOffset);
            fbb.finish(fbb.endTable());
            return object.id;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final asnNotCreatedDateValue = const fb.Int64Reader()
                .vTableGetNullable(buffer, rootOffset, 16);
            final asnNotIdParam = const fb.Int64Reader().vTableGetNullable(
              buffer,
              rootOffset,
              6,
            );
            final asnNotLabelParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 8);
            final asnNotDescParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 10);
            final asnNotStatusParam = const fb.Int64Reader().vTableGetNullable(
              buffer,
              rootOffset,
              12,
            );
            final asnNotAscCompIdParam = const fb.Int64Reader()
                .vTableGetNullable(buffer, rootOffset, 14);
            final asnNotCreatedDateParam = asnNotCreatedDateValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(asnNotCreatedDateValue);
            final asnNotCreatedByParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 18);
            final object = NotificationResponseEntity(
              asnNotId: asnNotIdParam,
              asnNotLabel: asnNotLabelParam,
              asnNotDesc: asnNotDescParam,
              asnNotStatus: asnNotStatusParam,
              asnNotAscCompId: asnNotAscCompIdParam,
              asnNotCreatedDate: asnNotCreatedDateParam,
              asnNotCreatedBy: asnNotCreatedByParam,
            )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

            return object;
          },
        ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [LoginResponseEntity] entity fields to define ObjectBox queries.
class LoginResponseEntity_ {
  /// See [LoginResponseEntity.id].
  static final id = obx.QueryIntegerProperty<LoginResponseEntity>(
    _entities[0].properties[0],
  );

  /// See [LoginResponseEntity.result].
  static final result = obx.QueryStringProperty<LoginResponseEntity>(
    _entities[0].properties[1],
  );

  /// See [LoginResponseEntity.message].
  static final message = obx.QueryStringProperty<LoginResponseEntity>(
    _entities[0].properties[2],
  );

  /// See [LoginResponseEntity.username].
  static final username = obx.QueryStringProperty<LoginResponseEntity>(
    _entities[0].properties[3],
  );

  /// See [LoginResponseEntity.mainCompanyId].
  static final mainCompanyId = obx.QueryIntegerProperty<LoginResponseEntity>(
    _entities[0].properties[4],
  );

  /// See [LoginResponseEntity.comId].
  static final comId = obx.QueryIntegerProperty<LoginResponseEntity>(
    _entities[0].properties[5],
  );
}

/// [NotificationResponseEntity] entity fields to define ObjectBox queries.
class NotificationResponseEntity_ {
  /// See [NotificationResponseEntity.id].
  static final id = obx.QueryIntegerProperty<NotificationResponseEntity>(
    _entities[1].properties[0],
  );

  /// See [NotificationResponseEntity.asnNotId].
  static final asnNotId = obx.QueryIntegerProperty<NotificationResponseEntity>(
    _entities[1].properties[1],
  );

  /// See [NotificationResponseEntity.asnNotLabel].
  static final asnNotLabel =
      obx.QueryStringProperty<NotificationResponseEntity>(
        _entities[1].properties[2],
      );

  /// See [NotificationResponseEntity.asnNotDesc].
  static final asnNotDesc = obx.QueryStringProperty<NotificationResponseEntity>(
    _entities[1].properties[3],
  );

  /// See [NotificationResponseEntity.asnNotStatus].
  static final asnNotStatus =
      obx.QueryIntegerProperty<NotificationResponseEntity>(
        _entities[1].properties[4],
      );

  /// See [NotificationResponseEntity.asnNotAscCompId].
  static final asnNotAscCompId =
      obx.QueryIntegerProperty<NotificationResponseEntity>(
        _entities[1].properties[5],
      );

  /// See [NotificationResponseEntity.asnNotCreatedDate].
  static final asnNotCreatedDate =
      obx.QueryDateProperty<NotificationResponseEntity>(
        _entities[1].properties[6],
      );

  /// See [NotificationResponseEntity.asnNotCreatedBy].
  static final asnNotCreatedBy =
      obx.QueryStringProperty<NotificationResponseEntity>(
        _entities[1].properties[7],
      );
}
